services:
  inventory-db:
    image: postgres:16-alpine
    container_name: inventory-db
    restart: always
    environment:
      - POSTGRES_DB=${INVENTORY_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  billing-db:
    image: postgres:16-alpine
    container_name: billing-db
    restart: always
    environment:
      - POSTGRES_DB=${BILLING_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - billing-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  rabbit-queue:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbit-queue
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - backend-network

  inventory-app:
    build: ./srcs/inventory-app
    image: inventory-app
    container_name: inventory-app
    restart: always
    depends_on:
      - inventory-db
    env_file:
      - .env
    networks:
      - backend-network

  billing-app:
    build: ./srcs/billing-app
    image: billing-app
    container_name: billing-app
    restart: always
    env_file:
      - .env
    depends_on:
      - billing-db
      - rabbit-queue
    networks:
      - backend-network

  api-gateway-app:
    build: ./srcs/api-gateway-app
    image: api-gateway-app
    container_name: api-gateway-app
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - api-gateway-logs:/var/log/api-gateway
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  inventory-db-data:
  billing-db-data:
  api-gateway-logs: