services:
  inventory-db:
    build: ./srcs/postgres-image
    container_name: inventory-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_INVENTORY}
      - POSTGRES_USER=${POSTGRES_USER_INVENTORY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_INVENTORY}
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  billing-db:
    build: ./srcs/postgres-image
    container_name: billing-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB_BILLING}
      - POSTGRES_USER=${POSTGRES_USER_BILLING}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_BILLING}
    volumes:
      - billing-db-data:/var/lib/postgresql/data
    networks:
      - backend-network

  rabbit-queue:
    build: ./srcs/rabbit-queue
    container_name: rabbit-queue
    restart: unless-stopped
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672" # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    networks:
      - backend-network

  inventory-app:
    build: ./srcs/inventory-app
    image: inventory-app
    container_name: inventory-app
    restart: unless-stopped
    depends_on:
          inventory-db:
            condition: service_started
    env_file:
      - .env
    networks:
      - backend-network

  billing-app:
    build: ./srcs/billing-app
    image: billing-app
    container_name: billing-app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - billing-db
      - rabbit-queue
    networks:
      - backend-network

  api-gateway-app:
    build: ./srcs/api-gateway-app
    image: api-gateway-app
    container_name: api-gateway-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${API_GATEWAY_PORT}:3000"
    volumes:
      - api-gateway-logs:/var/log/api-gateway
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  inventory-db-data:
  billing-db-data:
  api-gateway-logs: 